CHANGELOG.md
src/functions/greetUser.js

I have...
Update welcome message
Closes #
[contributing]: https://github.com/BaalKrshna/welcome-bot/blob/main/.github/CONTRIBUTING.md

Update welcome message

---

docs/commands.md
src/functions/execute.js
src/functions/greetUser.js

Fix errors

---

CHANGELOG.md
README.md
package.json
src/bot.js
src/functions/greetUser.js
src/functions/serverCount.js

I have...
Fix bug and use embed to send welcome message
Closes #

Fix bug: not posting server count to botlist.space

---

.github/workflows/run-format.yml
CHANGELOG.md
package-lock.json
package.json
src/WelcomeBot.js
src/commands/fun/image.js
src/commands/fun/pokemon.js
src/commands/general/help.js
src/commands/info/info.js
src/commands/info/stats.js
src/commands/info/user.js
src/commands/mod/ban.js
src/commands/mod/kick.js
src/commands/mod/unban.js
src/commands/owner/reload.js
src/commands/owner/restart.js
src/commands/setup/enable.js
src/commands/setup/prefix.js
src/functions/execute.js
src/functions/greetUser.js
src/functions/presence.js
src/functions/randomImage.js

I have...
Upgrade to discord.js v13
Closes #

Upgrade to djs v13

---

CHANGELOG.md
commands.md
src/commands/anime/cuddle.js
src/commands/anime/hug.js
src/commands/anime/kiss.js
src/commands/info/botinfo.js

I have...
Replace this line with a description about the changes you have made in this PR (Correcting typos, adding new features, etc.)
Closes #

Fix bug & move hug, kiss, cuddle commands to anime.

---

README.md

I have...
Break out lines which are required to be in next line
And minor updates to readme
Closes #

fix(readme): Break out lines

---

package-lock.json
package.json
webserver.js

I have...
So add a simple webserver file. For the server to return 200 and our status page will show running, or else it will show down.
Closes #

fix: When deployment over, webserver will not start

---

Dockerfile

fix: Dockerfile should now start from webserver.js

---

src/commands/core/suggest.js

Fix suggest cmd

---

src/classes/Embed.js

I have...
Replace this line with a description about the changes you have made in this PR (Correcting typos, adding new features, etc.)
Closes #

fix: Embed class

---

src/classes/Embed.js

I have...
Replace this line with a description about the changes you have made in this PR (Correcting typos, adding new features, etc.)
Closes #

fix: last fix

---

CHANGELOG.md
src/commands/core/uptime.js

I have...
See commits
Closes #

fix: emoji in uptime cmd & remove footer

---

.github/CONTRIBUTING.md

I have...
Replace this line with a description about the changes you have made in this PR (Correcting typos, adding new features, etc.)
Closes #

docs: Improve contributing guidelines

---

.github/CONTRIBUTING.md

I have...
refactor means restructure not rewrite 😂. Sorry for my mistake
Closes #

fix(contributing guidelines)

---

src/bot.js
src/commands/general/help.js
src/functions/execute.js

I have...
https://github.com/discordjs/discord.js/pull/6035
Closes #

fix: Channel types are now uppercase

---

Dockerfile
package-lock.json
src/commands/owner/eval.js

I have...
Add `RUN npm update` to Dockerfile so that, we use the latest version of discord-player & discord.js too. And also use embeds for eval CMD.
Closes #

Fix Dockerfile & Use embeds for eval CMD

---

src/commands/setup/lang.js
src/helpers/Util.js

I have...
Before we used to set using `w/lang set hi-IN`. Now you can set using `w/lang set hindi`
Closes #

feat: Use Hindi for setting Hindi language not only hi-IN

---

src/commands/fun/coinflip.js
src/commands/fun/figlet.js
src/commands/fun/image.js
src/commands/fun/pokemon.js
src/commands/general/perms.js
src/locales/en-US/cmds.json

I have...
Some more translations!
Closes #

Add more translations

---

.github/workflows/ci.yml
.github/workflows/format.yml
.github/workflows/release-notes.yml
CHANGELOG.md
Dockerfile
commands.md
src/bot.js
src/classes/Command.js
src/commands/setup/disable.js
src/functions/execute.js
src/locales/en-US/cmds.json
src/locales/en-US/permissions.json

I have...
refactor(disable cmd): Disable commands using disable cmd now!
Changes
- Rename subcmd `show` to `display`
- Use embed for displaying current settings
Closes #

refactor(disable cmd): Disable commands using disable cmd now!

---

CHANGELOG.md
commands.md
src/commands/fun/emojify.js
src/locales/en-US/cmds.json
src/locales/en-US/errors.json

I have...
New cmd `emojify`
Closes #

feat: New cmd `emojify`

---

src/commands/general/perms.js
src/commands/general/user.js
src/commands/mod/mute.js
src/commands/mod/unmute.js

I have...
fix(general & mod cmds): Don't check if user id !== bot id
Closes #

fix(general & mod cmds): Don't check if user id !== bot id

---

CHANGELOG.md
src/commands/setup/enable.js
src/locales/en-US/cmds.json

I have...
refactor(enable): enable commands using enable cmd
Closes #

refactor(enable): enable commands using enable cmd

---

CHANGELOG.md
src/commands/core/report.js
src/config.js
src/locales/en-US/cmds.json

I have...
New cmd `report`
Closes #

feat(commands): New cmd `report`

---

CHANGELOG.md
src/classes/Command.js
src/commands/core/botinfo.js
src/commands/core/botperms.js
src/commands/core/report.js
src/commands/core/suggest.js
src/commands/general/avatar.js
src/commands/general/help.js
src/commands/general/listemojis.js
src/commands/general/perms.js
src/commands/general/serverinfo.js
src/commands/mod/ban.js
src/commands/mod/kick.js
src/commands/mod/mute.js
src/commands/mod/unban.js
src/commands/mod/unmute.js
src/functions/execute.js
src/locales/en-US/cmds.json
src/locales/en-US/errors.json
src/locales/en-US/misc.json

I have...
Lot more translations
Closes #

 refactor(translations): a lot more translations

---

CHANGELOG.md
package.json
src/commands/fun/duck.js
src/locales/en-US/cmds.json

I have...
Added duck cmd. Note: this command won't work until #159 is merged, but you can still merge it to v2 branch.
Closes #

feat(cmds): add duck cmd

---

CHANGELOG.md
src/commands/general/membercount.js
src/commands/general/serverinfo.js
src/locales/en-US/cmds.json

I have...
New command membercount
Closes #152

feat: New cmd `membercount`

---

.eslintrc.json
src/commands/setup/goodbye.js
src/commands/setup/welcome.js

fix(eslint)

---

src/commands/owner/shell.js

I have...
Added a shell command.
Closes #172

feat: New cmd `shell`

---

CHANGELOG.md
package.json
src/WelcomeBot.js
src/bot.js
src/commands/core/support.js
src/commands/general/chanid.js
src/commands/general/roleid.js
src/commands/general/serverid.js
src/commands/general/userid.js
src/helpers/Util.js
src/helpers/updateDocs.js
src/locales/en-US/cmds.json
src/locales/en-US/errors.json

I have...
Did whatever described in #84
Closes #84

feat: New cmds `chanid`, `roleid`, `serverid`, `userid`

---

CHANGELOG.md
package.json
src/bot.js
src/commands/core/ping.js
src/commands/economy/inventory.js
src/commands/general/reverse.js
src/locales/en-US/cmds.json

I have...
New command reverse
Closes #205

feat: New cmd `reverse`

---

TRANSLATORS.md

i have add my name to translator

docs(translators): add PeterLe

---

commands.md
src/commands/general/stealemoji.js
src/events/guildMemberUpdate.js
src/events/messageDelete.js
src/events/messageUpdate.js
src/loaders/Event.js
src/locales/en-US/misc.json

fix: multiple fixes

---

CHANGELOG.md
commands.md
package.json
src/commands/mod/lock.js
src/commands/mod/unlock.js
src/dashboard/app.js
src/locales/en-US/cmds.json

I have...
New commands: `lock` & `unlock`
Closes #

feat: New cmd `lock` & `unlock`

---

CHANGELOG.md
commands.md
package-lock.json
package.json
src/bot.js
src/commands/admin/config.js
src/commands/core/support.js
src/commands/mod/dehoist.js
src/events/guildCreate.js
src/events/guildMemberUpdate.js
src/events/interactionCreate.js
src/events/messageCreate.js
src/events/messageDelete.js
src/events/messageUpdate.js
src/functions/execute.js
src/helpers/Util.js
src/loaders/Command.js
src/locales/en-US/cmds.json

I have...
New command dehoist
Closes #

feat: New cmd `dehoist`

---

CHANGELOG.md
package.json
src/commands/general/screenshot.js
src/locales/en-US/cmds.json

I have...
New command screenshot
Closes #

feat: New cmd `screenshot`

---

.github/workflows/publish-dev.yml
CHANGELOG.md
package.json
src/classes/Embed.js
src/commands/admin/lang.js

I have...
fix language command
Closes #

fix(lang): fix bug not replying after setting language

---

src/locales/en-US/dashboard.json

I have...
I had written daisplay for display. Lol
Closes #

fix(locales): fix typo in dashboard:noGuildBody 🐛

---

CHANGELOG.md
package.json
src/commands/music/play.js
src/locales/en-US/cmds.json

I have...
Just add yt support back again
Closes #

refactor(play): support YT again

---

src/events/messageCreate.js

I have...
Title tells everything
Closes #

fix(messageCreate): do reply if guild id not added to db

---

src/events/messageCreate.js

TypeError: Cannot read properties of null (reading 'type')
I have...
fix error `TypeError: Cannot read properties of null (reading 'type')` in messageCreate event
TODO: update changelog
Closes #

fix(messageCreate): message.channel is nullable

---

CHANGELOG.md
package.json
src/functions/execute.js

I have...
fix execute function
Closes #

fix(execute): Array#includes not Array#has

---

package-lock.json
src/events/messageCreate.js
src/functions/greetUser.js

fix(greetUser): minor bug fixes
